version: '3.8'

networks:
  eshop_network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - eshop_network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    networks:
      - eshop_network
    ports:
      - "6379:6379"

  spring-boot-app:
    build:
      context: eshop
      dockerfile: Dockerfile
    container_name: spring-boot-app
    networks:
      - eshop_network
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mongodb_data:
